# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - '*'
  pr:
    branches:
      include:
        - '*'

jobs:
  - job: InstallDependencies
    displayName: 'Install Dependencies'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm install

  - job: Lint
    displayName: 'Lint'
    dependsOn: InstallDependencies
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm run lint

  - job: Formatter
    displayName: 'Formatter'
    dependsOn: Lint
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm run prettier

  - job: Test
    displayName: 'Test'
    dependsOn: Formatter
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: CI=true npm run test

  - job: Build
    displayName: 'Build'
    dependsOn: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm run build



