version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.11
    parallelism: 4
    steps:
      - checkout

      - run: npm install

      - run: npm run lint

      - run: npm run prettier

      - run: CI=true npm run test

      - run: npm run build

workflows:
  version: 2
  build:
    jobs:
      - build
