version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.11
    parallelism: 4
    steps:
      - checkout

        - run:
          command: ls /home/circleci/my-project/src/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Linter (ESLint)
          command: npm run lint
      - run:
          name: Formatter (Prettier)
          command: npm run prettier
      - run:
          name: Test (Jest)
          command: CI=true npm run test
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
