version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Install NVM and Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm install 14

      - run:
          name: Set working directory
          command: cd $CIRCLE_WORKING_DIRECTORY

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Linter (ESLint)
          command: npm run lint

      - run:
          name: Formatter (Prettier)
          command: npm run prettier

      - run:
          name: Test (Jest)
          command: CI=true npm run test

      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
