version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Linter (ESLint)
          command: npm run lint

      - run:
          name: Formatter (Prettier)
          command: npm run prettier

      - run:
          name: Test (Jest)
          command: CI=true npm run test

      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
