version: 2.1
workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - '*'
            pull_requests:
              only:
                - '*'
      - linter:
          filters:
            branches:
              only:
                - '*'
            pull_requests:
              only:
                - '*'
      - formatter:
          filters:
            branches:
              only:
                - '*'
            pull_requests:
              only:
                - '*'
      - test:
          filters:
            branches:
              only:
                - '*'
            pull_requests:
              only:
                - '*'
      - build:
          filters:
            branches:
              only:
                - '*'
            pull_requests:
              only:
                - '*'

jobs:
  install-dependencies:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install

  linter:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm run lint

  formatter:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm run prettier

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: CI=true npm run test

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm run build
